services:

  app:
    build: ./app
    environment:
      - PORT=3000
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=secret
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/redis-data:/var/lib/redis
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
